myproject/leaderboard/views.py
from re import search
from flask import Blueprint, render_template, redirect, url_for
from myproject import db,g
from myproject.models import Student
from sqlalchemy import asc
from myproject.search.form import Searching

leaderboard_blueprint = Blueprint('leaderboard', __name__, template_folder='templates/leaderboard')

@leaderboard_blueprint.route('/' , methods = ['GET', 'POST'])
def display_leaderboard():
    searchForm = Searching()
    if searchForm.searched.data != '' and  searchForm.validate_on_submit():
        return redirect(url_for('search.searching', searched = searchForm.searched.data))

    # leaderboard contains all the students with score > 0 in descending order
    leaderboard = Student.query.order_by(Student.student_rank.asc()).filter(Student.student_score > 0)

    return render_template('leaderboard.html', leaderboard = leaderboard, searchForm = searchForm, teacherLoggedIn = g.teacherLoggedIn)

myproject/students/views.py
from flask import Blueprint,render_template,redirect,url_for,flash,session,request
from flask_login import login_user,login_required,logout_user,current_user
from myproject import db,g
from myproject.models import Student, Teacher, Settings,Students_in_Classroom,Solved_Classroom_Assignment,Solved_Assignemnts,Assignment_Review, Assignments
from myproject.students.forms import SignUp,LogIn,ProfileTab,AccountTab,PrivacyTab,DeactivateTab
from myproject.search.form import Searching
from sqlalchemy import func, and_

students_blueprint = Blueprint('students', __name__ , template_folder='templates/students')

@students_blueprint.route('/signup',  methods=['GET', 'POST'])
def signup():
    searchForm = Searching()
    if searchForm.searched.data != '' and  searchForm.validate_on_submit():
        return redirect(url_for('search.searching', searched = searchForm.searched.data))
    
    form = SignUp()
    signupFailed1 = False
    signupFailed2 = False
    signupFailed3 = False

    if form.validate_on_submit():
        fname = form.fname.data
        lname = form.lname.data
        uname = form.uname.data
        email = form.email.data.lower()
        password1 = form.password1.data
        password2 = form.password2.data
        checkTeacherEmail = bool(Teacher.query.filter_by(teacher_email = email).first())
        checkStudentEmail = bool(Student.query.filter_by(student_email=email).first())
        checkTeacherUname = bool(Teacher.query.filter(func.lower(Teacher.teacher_uname) == func.lower(uname)).first())
        checkStudentUname = bool(Student.query.filter(func.lower(Student.student_uname) == func.lower(uname)).first())

         
        if checkTeacherUname or checkStudentUname: # Check if Uname is already taken
            return render_template('signup.html',form=form, signupFailed1 = True, searchForm = searchForm)      
        elif checkTeacherEmail or checkStudentEmail:  # Check if Email is already registered
            return render_template('signup.html',form=form, signupFailed2 = True, searchForm = searchForm)
       

        if password1 != '' and password1 == password2:
                new_student = Student(fname, lname, uname, email, password1, 0, 0, 0, 0, "", True, 4)
                db.session.add(new_student)
                db.session.commit()
                settings = Settings(new_student.id, True, True)
                db.session.add(settings)
                db.session.commit()
                return redirect(url_for('students.login'))
        else:
            return render_template('signup.html',form=form, signupFailed3 = True, searchForm = searchForm)
    
    return render_template('signup.html',form=form, searchForm = searchForm )


@students_blueprint.route('/login' , methods =['GET' , 'POST'])
def login():

    searchForm = Searching()
    if searchForm.searched.data != '' and  searchForm.validate_on_submit():
        return redirect(url_for('search.searching', searched = searchForm.searched.data))
    
    form = LogIn()
    loginFailed = False

    if form.validate_on_submit():
        email = form.email.data.lower()
        password = form.password.data

        CheckStudent = Student.query.filter_by(student_email = email).first()

        if CheckStudent != None and CheckStudent.student_email == email and CheckStudent.check_password(password):
            login_user(CheckStudent)

            next = request.args.get('next')
            if next == None or not next[0] == '/':
                next = url_for('index')

            # session['user'] = 'student'
            return redirect(next)
        else:
            return render_template('login.html' , form=form , loginFailed = True, searchForm = searchForm)

    return render_template('login.html', form=form, loginFailed = False, searchForm = searchForm)
            
@students_blueprint.route('/' )
@login_required
def signout():
    logout_user()
    return redirect( url_for('index') )

@students_blueprint.route('/profile',  methods =['GET' , 'POST'])
@login_required
def profile():
    searchForm = Searching()
    if searchForm.searched.data != '' and  searchForm.validate_on_submit():
        return redirect(url_for('search.searching', searched = searchForm.searched.data))

    form = ProfileTab()

    if form.validate_on_submit():
        user = Student.query.filter_by(student_email = current_user.student_email).first()
        if form.uname.data != "":

            CheckTeacher = bool(Teacher.query.filter(func.lower(Teacher.teacher_uname) == func.lower(form.uname.data)).first()) 
                                
            CheckStudent = bool(Student.query.filter(
                                and_(
                                        (func.lower(Student.student_uname) == func.lower(form.uname.data)),
                                        (func.lower(Student.student_uname) != func.lower(current_user.student_uname)),
                                    )
                                ).first())

            CheckUser = CheckTeacher or CheckStudent

            if not CheckUser:
                user.student_uname = form.uname.data
            else:
                pass

        if form.fname.data != "":
            user.student_fname = form.fname.data
        if form.lname.data != "":
            user.student_lname = form.lname.data
        if form.bio.data != "":
            user.student_bio = form.bio.data    
        db.session.add(user)
        db.session.commit()
        form.fname.data = ""
        form.lname.data = ""
        form.bio.data = ""
        form.uname.data = ""

    return render_template('profile.html', form = form, fname = current_user.student_fname, lname = current_user.student_lname, searchForm = searchForm )   


@students_blueprint.route('/photo'  , methods =['GET' , 'POST'])
@login_required
def photo():
    searchForm = Searching()
    if searchForm.searched.data != '' and  searchForm.validate_on_submit():
        return redirect(url_for('search.searching', searched = searchForm.searched.data))

    return render_template('photo.html',  fname = current_user.student_fname, lname = current_user.student_lname, searchForm = searchForm) 

@students_blueprint.route('/account',  methods =['GET' , 'POST'] )
@login_required
def account():
    searchForm = Searching()
    if searchForm.searched.data != '' and  searchForm.validate_on_submit():
        return redirect(url_for('search.searching', searched = searchForm.searched.data))
    
    form = AccountTab()
    passwordChangeFailed = False 
    passwordMatchFailed = False 

    if form.validate_on_submit():
        user = Student.query.filter_by(student_email = current_user.student_email).first()
        if not user.check_password(form.password1.data):
            passwordChangeFailed = True
            return render_template('account.html', form = form, fname = current_user.student_fname,
            lname = current_user.student_lname, passwordChangeFailed = passwordChangeFailed,passwordMatchFailed = passwordMatchFailed ,  searchForm = searchForm) 
            
        if form.password2.data == form.password3.data:
            user.hash_password(form.password2.data)
            db.session.add(user)
            db.session.commit()
        else:
            passwordMatchFailed = True

    return render_template('account.html', form = form, fname = current_user.student_fname,
        lname = current_user.student_lname, passwordChangeFailed = passwordChangeFailed ,passwordMatchFailed = passwordMatchFailed, searchForm = searchForm ) 

@students_blueprint.route('/payment_method' , methods =['GET' , 'POST'])
@login_required
def payment_method():
    searchForm = Searching()
    if searchForm.searched.data != '' and  searchForm.validate_on_submit():
        return redirect(url_for('search.searching', searched = searchForm.searched.data))

    return render_template('payment_method.html', fname = current_user.student_fname, lname = current_user.student_lname,  searchForm = searchForm)

@students_blueprint.route('/privacy',  methods =['GET' , 'POST']  )
@login_required
def privacy():
    searchForm = Searching()
    if searchForm.searched.data != '' and  searchForm.validate_on_submit():
        return redirect(url_for('search.searching', searched = searchForm.searched.data))

    user = Settings.query.filter_by(student_id= current_user.id).first()
    displayRankCheck = user.display_rank
    displayStatCheck = user.display_stats

    form = PrivacyTab()
    if form.validate_on_submit():
        
        if form.validate_on_submit():
            user.display_rank = form.displayRank.data
            user.display_stats = form.displayStats.data 
            displayRankCheck = user.display_rank
            displayStatCheck = user.display_stats   
            
            db.session.add(user)
            db.session.commit()
           
    return render_template('privacy.html', form = form,  fname = current_user.student_fname, lname = current_user.student_lname,  searchForm = searchForm, displayRankCheck = displayRankCheck, displayStatCheck = displayStatCheck )  

@students_blueprint.route('/deactivate_account' ,  methods =['GET' , 'POST'] )
@login_required
def deactivate_account():
    searchForm = Searching()
    if searchForm.searched.data != '' and  searchForm.validate_on_submit():
        return redirect(url_for('search.searching', searched = searchForm.searched.data))

    form = DeactivateTab()
    passwordMatchFailed = False 
    if form.validate_on_submit():
        user = Student.query.filter_by(student_email = current_user.student_email).first()
       
        if user.check_password(form.password.data):
            
            for q in Students_in_Classroom.query.filter_by(student_id = current_user.id).all():
                db.session.delete(q)
            
            for q in Solved_Classroom_Assignment.query.filter_by(student_id = current_user.id).all():
                db.session.delete(q)
            

myproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/../static/style.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="/../static/styles.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.3/js/bootstrap.bundle.min.js"></script>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Monda&family=Open+Sans+Condensed:wght@300&display=swap');
    </style>
    <script defer src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" integrity="sha384-9/D4ECZvKMVEJ9Bhr3ZnUAF+Ahlagp1cyPC7h5yDlZdXs4DQ/vRftzfd+2uFUuqS" crossorigin="anonymous"></script>
    <title>RatorX</title>
    {% if request.endpoint == 'assignments.solve_assignment' or request.endpoint == 'assignments.delete_assignment' or  request.endpoint == 'assignments.after_submit' %}
        <link href="{{ url_for('static', filename='style.css') }}" rel="stylesheet" type="text/css">
    {% endif %}
</head>
<body>
    <div class="wrapper" >
        <!-- nav barr -->
        <div class="nav">
            <div class="navleft">
                <ul>
                    <li><a class="brand" href="{{ url_for('index') }}">RatorX</a> </li>
                    <li> 
                        <div class="dropdown" onclick="myFunction2()">
                            <button class="dropbtn" style="display: flex;" >
                                <div   class="notBrand dropdown"> Top Categories</div>
                                <i  class="fa fa-caret-down dropdown" style="color: white; margin-left:5px; margin-top:15px"></i>
                            </button>
                            <div class="dropdown-content dropdown-content2" id="myDropdown2">
                                    <a href="{{url_for('assignments.categories', category = 1 )}}">Database</a>
                                    <a href="{{url_for('assignments.categories', category = 5 )}}">Data Structures</a>
                                    <a href="{{url_for('assignments.categories', category = 6 )}}">Object Oriented Programming</a>
                                    <a href="{{url_for('assignments.categories', category = 2 )}}">Software Development And Analysis</a>
                                    <a href="{{url_for('assignments.categories', category = 8 )}}">Physics</a>
                                    <a href="{{url_for('assignments.categories', category = 9 )}}">Chemistry</a>
                                    <a href="{{url_for('assignments.categories', category = 10)}}">Mathematics</a>
                                    <a href="{{url_for('assignments.categories', category = 11 )}}">English</a>
                                    <a href="{{url_for('assignments.categories', category = 12 )}}">Web Development</a>
                                    <a href="{{url_for('assignments.categories', category = 13 )}}">Web Scrapping</a>
                                    <a href="{{url_for('assignments.categories', category = 0)}}">All Courses</a>
                            </div>
                        </div> 
                    </li>
                    <form class="search_bar" method="POST">
                        {{ searchForm.hidden_tag() }}
                        <div class = "search_icon">
                            <i class="fas fa-search"> </i>
                            {{searchForm.submit( class =" search_btn")}}
                        </div>
                        <div class = "type_text">
                            {{ searchForm.searched(class = "input" , placeholder="Search for anything") }}
                        </div>
                    </form>

                </ul>
            </div>
            <div class="navright">
                <ul>
                    {% if current_user.is_authenticated %}
                        <li><a href="{{url_for('leaderboard.display_leaderboard')}}">Leaderboard</a></li>
                        <li>
                            <div class="dropdown" onclick="myFunction()">
                                <button class="dropbtn" >
                                    <a href="{{ url_for('students.profile') }}">{{current_user.student_fname|capitalize }}</a>
                                    <i class="fa fa-caret-down"></i>
                                </button>
                                <div class="dropdown-content" id="myDropdown">
                                    <a href="{{ url_for('classrooms.student_class_list') }}"> Your Classrooms</a>
                                    <a href="{{ url_for('students.signout') }}">SignOut</a>
                                </div>
                            </div> 
                        </li>
                    {% elif teacherLoggedIn %}
                        <li><a href="{{ url_for('assignments.list_assignment') }}">Assignments</a></li> 
                        <li>
                            <div class="dropdown" onclick="myFunction()">
                                <button class="dropbtn" >
                                  <a  href="{{ url_for('teachers.profile') }}">Profile</a>
                                  <i class="fa fa-caret-down"></i>
                                </button>
                                <div class="dropdown-content" id="myDropdown">
                                    <a href="{{url_for('classrooms.teacher_class_list')}}">Your Classrooms</a>
                                    <a href="{{url_for('leaderboard.display_leaderboard')}}">Leaderboard</a>
                                    <a href="{{ url_for('teachers.signout') }}">SignOut</a>
                                </div>
                            </div> 
                        </li>
                    {% else %}
                        <li><a href="{{ url_for('students.login') }}">Log in</a></li>
                        <li><a href="{{ url_for('students.signup') }}">Sign up</a></li>
                    {% endif %}    

                </ul>
            </div>
        </div>

        <script>
            /* When the user clicks on the button, 
            toggle between hiding and showing the dropdown content */
            function myFunction() {
              document.getElementById("myDropdown").classList.toggle("show");
            }
            function myFunction2() {
                document.getElementById("myDropdown2").classList.toggle("show");
            }
            
            // Close the dropdown if the user clicks outside of it
            window.onclick = function(e) {
              if (!e.target.matches('.dropbtn')) {
                var myDropdown = document.getElementById("myDropdown");
                    if (myDropdown.classList.contains('show')) {
                        myDropdown.classList.remove('show');
                    }
                var myDropdown2 = document.getElementById("myDropdown2");
                if (myDropdown2.classList.contains('show')) {
                    myDropdown2.classList.remove('show');
                } 
              }
            }
            window.onclick = function(e) {
                if (!e.target.matches('.dropbtn')) {
                var myDropdown2 = document.getElementById("myDropdown2");
                if (myDropdown2.classList.contains('show')) {
                    myDropdown2.classList.remove('show');
                }
                }

            } 
        </script>

        <!-- nav barr ends -->
        {% block content %}

        {% endblock %}

    </div>  
</body>
</html>

myproject/templates/baseProfile.html
{% extends "base.html" %}
{% block content %}

        <div class="mainDivPP">
            <div class="side">
                <div class="up">
                        <div class="pp" style="text-transform: uppercase;">
                            {{fname[0]|capitalize}}{{lname[0]|capitalize}}
                        </div>
                        <h5 id="uname">{{fname|capitalize}} {{" "}} {{lname|capitalize}}</h5>
                </div>
                
                <ul id="sideul">
                  {% if current_user.is_authenticated %}
                  <li> <a href="{{ url_for('students.profile') }}">Profile</a></li>
                  <li> <a href="{{ url_for('students.photo') }}">Photo</a></li>
                  <li> <a href="{{ url_for('students.account') }}">Account</a></li>
                  <li> <a href="{{ url_for('students.payment_method') }}">Payment Method</a></li>
                  <li> <a href="{{ url_for('students.privacy') }}">Privacy</a></li>
                  <li> <a href="{{ url_for('students.deactivate_account') }}">Close Account</a></li>
                  {% else %}
                  <li> <a href="{{ url_for('teachers.profile') }}">Profile</a></li>
                  <li> <a href="{{ url_for('teachers.photo') }}">Photo</a></li>
                  <li> <a href="{{ url_for('teachers.account') }}">Account</a></li>
                  <li> <a href="{{ url_for('teachers.payment_method') }}">Payment Method</a></li>
                  <li> <a href="{{ url_for('teachers.privacy') }}">Privacy</a></li>
                  <li> <a href="{{ url_for('teachers.deactivate_account') }}">Close Account</a></li>
                  {% endif %}
                </ul>

                <!-- <script>
                    // Add active class to the current button (highlight it)
                    var header = document.getElementById("sideul");
                    var selected = header.getElementsByClassName("sideli");
                    for (var i = 0; i < selected.length; i++) {
                      selected[i].addEventListener("click", function() {
                        var current = document.getElementsByClassName("active");
                        current[0].className = current[0].className.replace(" active", "");
                        this.className += " active";
                      });
                    }
                    </script> -->
                
            </div>
            
            <div class="content">
                {% block content2 %}

                {% endblock %}
                
            </div>
            
        </div> 

        {% endblock %}

myproject/templates/home.html
{% extends "base.html" %}
{% block content %}
<section class="top-container">
  <header class="showcase">
      <h1>Your Concept's Practice</h1>
      <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Rerum, laborum dignissimos quo placeat vero ad!</p> 
      <a href="#">Read More</a>
  </header>
  <div class="top-box top-box-a">
      
      <h4><i class="fab fa-readme iconx" style="margin: 0 3px;"></i>100,000+ Assignments</h4>
      <p>Enjoy the variety of Assignments</p>
  </div>
  <div class="top-box top-box-b">
      
      <h4><i class="fas fa-certificate iconx" style="margin: 0 3px;"></i></i>Expert Grading</h4>
      <p>Find the right instructor for you</p>
  </div>

  <div class="top-box top-box-c">
      
      <h4><i class="fas fa-infinity iconx" style="margin: 0 3px;"></i>Lifetime Access</h4>
      <p>Solve on your schedule</p>
  </div>
</section>
{% if current_user.is_authenticated and top_pick%}
        <section class="assignments">
          <div class="assignments_heading">
              <h1>Our Top Pick for you</h1>
              <hr id="hrbottom">
          </div>
        
          <div class="assignment_wrapper">
              <a href="{{url_for('assignments.solve_assignment', aid = top_pick.id)}}" class= "assignment_box"> 
                <div class="assignment_name">
                  {{top_pick.assignment_name}}
                </div>
                <div class="teacher_description">
                  {{top_pick.teacher.teacher_fname}} {{ " "}} {{ top_pick.teacher.teacher_lname}}
                </div>
                <div class="rate_review"> 
                  <div class = "rating"> {{ "$%.1f"|format(top_pick.assignment_rating) }}</div>
                  <div class = "reviews"> ({{top_pick.assignment_no_of_reviews}}) </div>
                </div>
                <div class="price">Free</div>
                <div class="status">New</div>
              </a>
          </div>
        </section>  
{% endif %}

<section class="assignments" style="margin-top:80px;">
  <div class="assignments_heading">
      <h1>The world's largest selection of assignments</h1>
      <p>Choose from 100,000+ assignments with new assignments uploaded everyday</p>
      <hr id="hrbottom">
  </div>
  

  <div class="assignment_wrapper">
    {% for assignment in all_assignments  %}
          <a href="{{url_for('assignments.solve_assignment', aid = assignment.id)}}" class= "assignment_box"> 
            <div class="assignment_name">
              {{assignment.assignment_name}}
            </div>
            <div class="teacher_description">
              {{assignment.teacher.teacher_fname}} {{ " "}} {{ assignment.teacher.teacher_lname}}
            </div>
            <div class="rate_review"> 
              <div class = "rating"> {{ "$%.1f"|format(assignment.assignment_rating) }}</div>
              <div class = "reviews"> {{"("}}{{assignment.assignment_no_of_reviews}}{{")"}} </div>
            </div>
            <div class="price">Free</div>
            <div class="status">New</div>
          </a>
    {% endfor %}
  </div>
</section>

{% if current_user.is_authenticated %}
    {% if recomended_assignments_x[0] %}
    
      <section class="assignments" style="margin-top: 80px;">
        <div class="assignments_heading">
            <h1 style="color: rgba(0,0,0,0.8); font-size: 28px; font-weight:700">Because you solved "{{recomended_assignments_x[0].course.course_name|capitalize}}" assignments </h1>
            <hr id="hrbottom">
        </div>
        <div class="assignment_wrapper">
          {% for assignment in recomended_assignments_x  %} 
                <a href="{{url_for('assignments.solve_assignment', aid = assignment.id)}}" class= "assignment_box"> 
                  <div class="assignment_name">
                    {{assignment.assignment_name}}
                  </div>
                  <div class="teacher_description">
                    {{assignment.teacher.teacher_fname}} {{ " "}} {{ assignment.teacher.teacher_lname}}
                  </div>
                  <div class="rate_review"> 
                    <div class = "rating"> {{ "$%.1f"|format(assignment.assignment_rating) }}</div>
                    <div class = "reviews"> {{"("}}{{assignment.assignment_no_of_reviews}}{{")"}} </div>
                  </div>
                  <div class="price">Free</div>
                  <div class="status">New</div>
                </a>
          {% endfor %}
        </div>
      </section>
    {% endif %}

    {% if recomended_assignments_y[0] %}
      <section class="assignments" style="margin-top: 80px;">
        <div class="assignments_heading">
            <h1 style="color: rgba(0,0,0,0.8); font-size: 28px; font-weight:700">Because you solved "{{recomended_assignments_y[0].course.course_name|capitalize}}" assignments </h1>
            <hr id="hrbottom">
        </div>
        <div class="assignment_wrapper">
          {% for assignment in recomended_assignments_y  %} 
                <a href="{{url_for('assignments.solve_assignment', aid = assignment.id)}}" class= "assignment_box"> 
                  <div class="assignment_name">
                    {{assignment.assignment_name}}
                  </div>
                  <div class="teacher_description">
                    {{assignment.teacher.teacher_fname}} {{ " "}} {{ assignment.teacher.teacher_lname}}
                  </div>
                  <div class="rate_review"> 
                    <div class = "rating"> {{ "$%.1f"|format(assignment.assignment_rating) }}</div>
                    <div class = "reviews"> {{"("}}{{assignment.assignment_no_of_reviews}}{{")"}} </div>
                  </div>
                  <div class="price">Free</div>
                  <div class="status">New</div>
                </a>
          {% endfor %}
        </div>
      </section> 
    {% endif %}
    
    {% if recomended_assignments_z[0] %}
      <section class="assignments" style="margin-top: 80px;">
        <div class="assignments_heading">
            <h1 style="color: rgba(0,0,0,0.8); font-size: 28px; font-weight:700">Because you solved "{{recomended_assignments_z[0].course.course_name|capitalize}}" assignments </h1>
            <hr id="hrbottom">
        </div>
        <div class="assignment_wrapper">
          {% for assignment in recomended_assignments_z  %} 
                <a href="{{url_for('assignments.solve_assignment', aid = assignment.id)}}" class= "assignment_box"> 
                  <div class="assignment_name">
                    {{assignment.assignment_name}}
                  </div>
                  <div class="teacher_description">
                    {{assignment.teacher.teacher_fname}} {{ " "}} {{ assignment.teacher.teacher_lname}}
                  </div>
                  <div class="rate_review"> 
                    <div class = "rating"> {{ "$%.1f"|format(assignment.assignment_rating) }}</div>
                    <div class = "reviews"> {{"("}}{{assignment.assignment_no_of_reviews}}{{")"}} </div>
                  </div>
                  <div class="price">Free</div>
                  <div class="status">New</div>
                </a>
          {% endfor %}
        </div>
      </section>  
    {% endif %}
{% endif %}

<section class="info">
  <img src="../static/pic1.jpg" alt="" style="width: 100%;">
  <div>
      <h2>Your Practice on the web</h2>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maiores, quaerat fugiat. Cumque quia id illum fugiat, odio enim nesciunt voluptatem ipsam earum deleniti cum sunt, libero vero! Eos ab maxime quos consectetur blanditiis in distinctio, mollitia veritatis est minima vitae sint, odit dolorem quibusdam saepe inventore officiis suscipit enim. Beatae sed quia soluta aspernatur, quam maiores nam earum quaerat totam!</p>
      <a href="#">Learn More</a>
  </div>
  
  
  
</section>

<hr style="background:black solid;">
<footer> 
  <p>RatorX &copy; 2020</p>
</footer>
{% endblock %}