myproject/assignments/views.py
from flask import Blueprint,render_template,redirect,url_for,flash,session
from flask_login import login_required,current_user
from myproject import db,g
from myproject.models import Student, Teacher, Assignments, Assignment_Data, Courses, Assignment_Review, Solved_Assignemnts, Assignments_in_Classroom, Solved_Classroom_Assignment
from myproject.assignments.forms import SolveAssignment, AddAssignment, DeleteAssignment, SubmitAssignment
from wtforms import RadioField,SubmitField, StringField,SelectField, Form, validators
from myproject.search.form import Searching
from sqlalchemy import func, and_ , inspect
import time

assignments_blueprint = Blueprint('assignments', __name__ , template_folder='templates/assignments')

@assignments_blueprint.route('/<category>',  methods=['GET', 'POST'])
def categories(category):
    courses = None
    if int(category) == 1:
        assignments = Assignments.query.filter_by(course_id = 1)
    elif int(category) == 2:
        assignments = Assignments.query.filter_by(course_id = 2)
    elif int(category) == 5:
        assignments = Assignments.query.filter_by(course_id = 5)
    elif int(category) == 6:
        assignments = Assignments.query.filter_by(course_id = 6)
    elif int(category) == 8:
        assignments = Assignments.query.filter_by(course_id = 8)
    elif int(category) == 9:
        assignments = Assignments.query.filter_by(course_id = 9)
    elif int(category) == 10:
        assignments = Assignments.query.filter_by(course_id = 10)
    elif int(category) == 11:
        assignments = Assignments.query.filter_by(course_id = 11)
    elif int(category) == 12:
        assignments = Assignments.query.filter_by(course_id = 12)
    elif int(category) == 13:
        assignments = Assignments.query.filter_by(course_id = 13)
    else:
        assignments = None
        courses = Courses.query.all()
    #endif

    if assignments == None:
        assignments = Assignments.query.filter_by(course_id = int(category))
    


    searchForm = Searching()
    if searchForm.searched.data != '' and  searchForm.validate_on_submit():
        return redirect(url_for('search.searching', searched = searchForm.searched.data))

    return render_template('display_category.html', assignments = assignments, teacherLoggedIn = g.teacherLoggedIn, searchForm = searchForm, courses=courses )


@assignments_blueprint.route('/description',  methods=['GET', 'POST'])
def description():
    searchForm = Searching()
    if searchForm.searched.data != '' and  searchForm.validate_on_submit():
        return redirect(url_for('search.searching', searched = searchForm.searched.data))

    return render_template('description.html' , teacherLoggedIn = g.teacherLoggedIn,searchForm = searchForm)

@assignments_blueprint.route('/add_assignment',  methods=['GET', 'POST'])
def add_assignment():
    searchForm = Searching()
    if searchForm.searched.data != '' and searchForm.validate_on_submit():
        return redirect(url_for('search.searching', searched = searchForm.searched.data))

    course = SelectField("Courses",[validators.Required()], choices = [(course.id, course.course_name) for course in Courses.query.all()])
    setattr(AddAssignment, 'course', course)
 

    all_questions = [] 
    questions = []
    index = []
    assignment_questions = 1
    for x in range (1): #for no of questions
        field = StringField([ validators.Required() ])
        setattr(AddAssignment, 'Question' + str(assignment_questions), field)
        questions.append('Question' + str(assignment_questions))
        choice = 1
        for y in range (4):
            setattr(AddAssignment, 'Choice' + str(assignment_questions) + str(choice), field)
            questions.append('Choice' + str(assignment_questions) + str(choice))
            choice += 1
        setattr(AddAssignment, 'Answer' + str(assignment_questions), field)
        questions.append('Answer' + str(assignment_questions))
        index.append(str(assignment_questions))
        assignment_questions += 1
        all_questions.append(questions)
        questions = []
    setattr(AddAssignment, 'submit', SubmitField('Add Assignment') )


    form = AddAssignment()

    if form.validate_on_submit():
        assignment_name = form.assignment_name.data
        difficulty = form.difficulty.data
        course_id = form.course.data

        updated_course = Courses.query.filter_by(id = course_id).first()
        updated_course.no_of_assignments += 1  #incrementing the number of assignments for a course
        db.session.add(updated_course)
        db.session.commit()
        
        CheckAssignment = bool(Assignments.query.filter(func.lower(Assignments.assignment_name) == func.lower(assignment_name)).first())

        if not CheckAssignment:
            new_assignment = Assignments(assignment_name, course_id, difficulty, 0, 0, 0, 1, g.whichTeacher.id)
            db.session.add(new_assignment)
            db.session.commit()

            question = []
            for x in range(1,assignment_questions): 
                question.append(new_assignment.id)
                question.append(x)
                question.append( getattr( form , 'Question' + str(x) ).data )
                for y in range(1,5):
                    question.append( getattr(form,'Choice' + str(x) + str(y)).data )

                question.append (getattr(form, 'Answer' + str(x)).data )

                new_question = Assignment_Data(question[0], question[1], question[2], question[3], question[4], question[5], question[6], question[7])
                db.session.add(new_question)
                db.session.commit()
                question = []
        else:
            pass
        
        return redirect(url_for('assignments.list_assignment'))

    return render_template('add_assignment.html', all_questions = all_questions, index = index, form = form, teacherLoggedIn = g.teacherLoggedIn,searchForm = searchForm)





@assignments_blueprint.route('/delete_assignment/<aid>',  methods=['GET', 'POST'])
def delete_assignment(aid):
    searchForm = Searching()
    if searchForm.searched.data != '' and searchForm.validate_on_submit():
        return redirect(url_for('search.searching', searched = searchForm.searched.data))
    
    assignment_data = Assignment_Data.query.filter_by(assignment_id = aid).all()
    no_of_question = 0
    for question in assignment_data:
        no_of_question +=1
    
    if assignment_data[0].assignment.difficulty == 'Expert':
        total_points = 5* (no_of_question)
        points = 5
    elif assignment_data[0].assignment.difficulty == 'Intermediate':
        total_points = 3* (no_of_question)
        points = 3
    else:
        total_points = 1* (no_of_question)
        points = 1

    form = DeleteAssignment()
    #try with multiple questions
    if form.validate_on_submit():
      

        assignment = Assignments.query.filter_by(id = aid).first()
        updated_course = Courses.query.filter_by(id = assignment.course_id).first()
        if updated_course.no_of_assignments == 0:
            updated_course.no_of_assignments = 0
        else:
            updated_course.no_of_assignments -= 1  #incrementing the number of assignments for a course
        db.session.add(updated_course)
        db.session.commit()
      
        assignment = Assignments.query.filter_by(id = aid).first()
        db.session.delete(assignment)
        db.session.commit()

        # Now updating Teacher teacher_rating and teacher_no_Of_reviews.
        teacher = Teacher.query.filter_by(id = g.whichTeacher.id).first()
        teacher_assignments = Assignments.query.filter_by(teacher_id = teacher.id).all()

        count = 0
        avg_teacher_rating = 0
        for assignment in teacher_assignments:
            if assignment.assignment_rating > 0:
                count += 1
                avg_teacher_rating += assignment.assignment_rating
            #endif
        #endfor

        if count == 0:
            teacher.teacher_rating = 0
            teacher.teacher_no_Of_reviews = 0
        else:    
            teacher.teacher_rating = avg_teacher_rating/count
            teacher.teacher_no_Of_reviews -= assignment.assignment_no_of_reviews
        #endif
        db.session.add(teacher)
        db.session.commit()

        return redirect(url_for('assignments.list_assignment'))

    return render_template('delete_assignment.html', form = form, teacherLoggedIn = g.teacherLoggedIn, assignment_data = assignment_data, searchForm = searchForm, total_points = total_points , points =points )


@assignments_blueprint.route('/list_assignment', methods=['GET', 'POST'])
def list_assignment():
    searchForm = Searching()
    if searchForm.searched.data != '' and  searchForm.validate_on_submit():
        return redirect(url_for('search.searching', searched = searchForm.searched.data))

    all_assignments = Assignments.query.filter_by(teacher_id = g.whichTeacher.id)
    teacher = Teacher.query.filter_by(id = g.whichTeacher.id).first()
    
    total_assignments = 0
    for assignment in all_assignments:
        total_assignments += 1
    
    return render_template('list_assignment.html',teacher = teacher, all_assignments=all_assignments, teacherLoggedIn = g.teacherLoggedIn, searchForm = searchForm, total_assignments=total_assignments)

@assignments_blueprint.route('/solve_assignment/<aid>',  methods=['GET', 'POST'])
@login_required
def solve_assignment(aid):

    # ----------Searching Section------------
    searchForm = Searching()
    if searchForm.searched.data != '' and  searchForm.validate_on_submit():
        return redirect(url_for('search.searching', searched = searchForm.searched.data))

    questions = Assignment_Data.query.filter_by(assignment_id = aid)

    #-----------Making a form------------------
    no_of_question = 1
    field_list = []

    for record in questions:

myproject/assignments/templates/assignments/add_assignment.html
{% extends "base.html" %}
{% block content %}
    <div class="add_assignment_wrapper" >
        <div class = "main_heading">
            Add New Assignment
        </div>
        <form method="POST" class="add_assignment">
            <div class="assignment_details">
                {{ form.hidden_tag() }}
                <div class="form_labels">
                    <p class = "field1"> Assignment Name: </p>
                    <p class = "field2"> Select Difficulty: </p>
                    <p class = "field3"> Select Course: </p>
                </div>
                <div class="form_fields">
                     {{ form.assignment_name( class = "fields") }} 
                     {{ form.difficulty(class = "fields" , style = "width:230px;") }} 
                     {{ form.course(class = "fields") }} 
                </div>   
            </div>
            <div class="questions_details" >
                <div class="question">
                {% for question in all_questions %}
                    <p class = "question_no">QUESTION {{index[loop.index0] }}</p>
                    {{ form|attr(question[0])(placeholder="",class =  'field question_field') }} 
                    {{ form|attr(question[1])(placeholder= "Choice 1", class = 'field choice_field') }} 
                    {{ form|attr(question[2])(placeholder= "Choice 2", class = 'field choice_field') }} 
                    {{ form|attr(question[3])(placeholder= "Choice 3", class = 'field choice_field') }} 
                    {{ form|attr(question[4])(placeholder= "Choice 4", class = 'field choice_field') }} 
                    {{ form|attr(question[5])(placeholder= "Answer(1-4)", class = 'field answer_field') }}
                {% endfor %}
                </div>
            </div>

           <div class="add_assignmnet_btn_div">
                
                <div class="add_assignment_btn2"> Add Question</div>
                {{ form.submit(class="add_assignment_btn") }}
                
           </div>

    
            
        </form>
    </div>
    
{% endblock %}

myproject/assignments/templates/assignments/after_submit.html
{% extends "base.html" %}
{% block content %}
    <div class="after_submit_wrapper">           
        {% if passed == 'True' %}
                <div class="result">
                    <h4>You Passed!</h4>
                    <h6>Points Earned: {{points_earned}} </h6>
                    <h6>  Total Points: {{ current_user.student_score}} </h6>
                    {% if rank_changed %}
                        {% if old_rank > current_user.student_rank %}
                            <h6 style="color: green;"> Your Rank is increased from {{old_rank}} to {{current_user.student_rank}} </h6>
                        {% else %}
                            <h6 style="color: green;"> Your Rank is decreased from {{old_rank}} to {{current_user.student_rank}} </h6>
                        {% endif %}
    
                        <h6>Your New Rank: {{ current_user.student_rank}} </h6>
                    {% else %}
                        <h6> Your Rank: {{ current_user.student_rank}} </h6>
                    {% endif %}
                </div>        
        {% else %}
                <div class="result fail">
                    <h4 style="color: red;">You Failed! </h4>
                    <h6> Your Rank: {{ current_user.student_rank}} </h6>
                </div>     
        {% endif %}
    
         
        

        {% if review_already_given %}
                <div class="your_review">
                    <div class="rating">
                        <p class="rating_label">Your Rating:</p>
                        <div class="rating_field" >
                            {{review_already_given.assignment_rating}} / 5.0
                        </div>
                    </div>
                    <div class="review">
                        <p class="review_label">Your Review:</p>
                        <div class = "review_field"> 
                            <p>{{review_already_given.review_text}} </p>
                        </div>

                    </div>
                </div>
             
        {% else %}
            <form method="POST" class="give_review">
                {{ form.hidden_tag() }}
                <div class="rating">
                    <p class="rating_label">Rate this Assignment:</p>
                    {{ form.rating(class="rating_field") }} 
                </div>

                <div class="review">
                    <p class="review_label">Give this assignment a review</p>
                    {{ form.review(class="review_field") }}
                </div>
                <div class="review_btn">
                    {{ form.submit(class="rate_review_btn") }}
                </div>
               
            </form>
        {% endif %}
                
    </div>
    
{% endblock %}

myproject/assignments/templates/assignments/delete_assignment.html
{% extends "base.html" %}
{% block content %}
<form method="POST">  
   <div class="attempt_page_wrapper">

        <div class="attempt_page_heading">
            <h1>{{assignment_data[0].assignment.assignment_name}}</h1>
            <div class = "delete_and_points"> 
                <p style="font-weight: bold">Total Points: {{total_points}}</p>
                {{ form.submit( class = "delete_assignment_btn")}} 
            </div>
            <hr style = "height:5px;">
        </div>

        <div class="attempt_page_solving">
                {{ form.hidden_tag() }}
                <!-- Outer Loop -->
                
                {% for assignment in assignment_data %}
                    <div class="form_fields">
                        <div class="ap_question">
                            <p>{{assignment.question_id}}.</p>
                            <p style="display: flex; justify-content: flex-start; align-items: center;  "> {{assignment.question_text}}</p>
                            <div style=" display:flex; flex-direction:column; justify-content:center; align-items:center">
                                <p style="
                                width: 90px ;margin-left: auto; border: solid 1px black; border-radius:15px;
                                display:flex; justify-content:center; position:sticky;
                                "> 
                                    {{points}} Points
                                </p>
                            </div>
                            
                        </div>
                        <div class="ap_options"></p>
                           <ul>
                               <li  >{{ assignment.choice1 }}</li>
                               <li>{{ assignment.choice2 }}</li>
                               <li>{{ assignment.choice3 }}</li>
                               <li>{{ assignment.choice4 }}</li>
                               <br>
                               <p style="font-weight: bold; color: green">Correct Answer: {{assignment.answer}}</p>
                           </ul> 
                        </div>
    
                        
                    </div> 
                    
                {% endfor %}

        </div>
 
   </div>
</form>  
{% endblock %}

myproject/assignments/templates/assignments/display_category.html
{% extends 'base.html' %}

{% block content %}
<section class="assignments" style="margin-top:50px;">
    
    {% if assignments[0] %}
    <div class="assignments_heading">
        <h1>{{assignments[0].course.course_name}} assignments</h1>
        <hr id="hrbottom">
    </div>
    <div class="assignment_wrapper">
        {% for assignment in assignments  %} 
            <a href="{{url_for('assignments.solve_assignment', aid = assignment.id)}}" class= "assignment_box"> 
                <div class="assignment_name">
                {{assignment.assignment_name}}
                </div>
                <div class="teacher_description">
                {{assignment.teacher.teacher_fname}} {{ " "}} {{ assignment.teacher.teacher_lname}}
                </div>
                <div class="rate_review"> 
                <div class = "rating"> {{ "$%.1f"|format(assignment.assignment_rating) }}</div>
                <div class = "reviews"> ({{assignment.assignment_no_of_reviews}}) </div>
                </div>
                <div class="price">Free</div>
                <div class="status">New</div>
            </a>
        {% endfor %}
    </div>
    {% else %}
    <div style="display:grid; grid-template-columns: repeat(4, 1fr); width:80%; margin: 0 10%;">
        {% for course in courses %}
                {% if course.course_name != 'Others'%}
                <div class="card" style="width: 18rem;height:12rem; margin:5% 0; box-shadow: 0px 0px 5px rgb(193, 193, 193)">    
                    <div class="card-body modifier">
                        <div>
                            <h5 class="card-title">{{ course.course_name }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted">Number of Assignments: {{course.no_of_assignments}}</h6>      
                        </div>
                      <a href="{{url_for('assignments.categories', category = course.id)}}" style="justify-content: flex-end;color: orangered; font-weight:500;" class="card-link">Browse all assignments</a>
                    </div>
                  </div>
                {%endif%}
        {% endfor %}
    </div>
        
    {% endif %}
</section>

<style>
    .modifier{
        display: flex;
        flex-direction: column;
        justify-content: space-between;
    }

</style>
    

{% endblock %}

myproject/assignments/templates/assignments/list_assignment.html
{% extends "base.html" %}
{% block content %}
    <div class="list_assignment_wrapper" > 
        <div class = list_top_container> 
             <div class="main_heading">
                <div class="heading"> Your Assignments </div>
                <a  class="add_assignment_btn" href="{{ url_for('assignments.add_assignment')}}">Add New Assignment <small><i class="fas fa-plus"></i></small></a>
            </div>
            
            <div class="stats">
                    <div>
                        STATS
                    </div>
                    <hr style="border: solid 1px orangered; margin: 0 17px; margin-bottom:10px; width:200px">
                    <div>
                        Active Assignments: {{total_assignments}}
                    </div>
                    <div>
                        Total Reviews: {{teacher.teacher_no_Of_reviews}}
                    </div>
                    <div>
                        Average  Rating: {{"%.1f"|format(teacher.teacher_rating)}}
                    </div>
            </div>
        </div >
        <hr style="margin-bottom:25px;">
        <div class="display_assignment">
            {% for assignment in all_assignments %}
                <a class= "assignment_box" href="{{ url_for('assignments.delete_assignment', aid = assignment.id) }}"> 
                    <div class="assignment_name">
                        {{assignment.assignment_name}}
                    </div>
                    <div class="teacher_description">
                        {{assignment.teacher.teacher_fname}} {{ " "}} {{ assignment.teacher.teacher_lname}}
                    </div>
                    <div class="rate_review">
                        <div class = "rating"> {{"$%.1f"|format(assignment.assignment_rating)}}</div>
                        <div class = "reviews"> ({{assignment.assignment_no_of_reviews}}) </div>
                    </div>
                    <div class="price">Free</div>
                    <div class="status">New</div>
                </a>

            {% endfor %}
        </div>
        
 
    </div>   
    
{% endblock %}

myproject/assignments/templates/assignments/solve_assignment.html
{% extends "base.html" %}
{% block content %}
    
    
   <div class="attempt_page_wrapper">

        <div class="attempt_page_heading">
            <h1>{{questions[0].assignment.assignment_name}}</h1>
            <p>Total Points: {{ total_points}}</p>
            <hr>
        </div>

        <div class="attempt_page_solving">
            <form method="POST">
                {{ form.hidden_tag() }}
                <!-- Outer Loop -->
                
                {% for question in questions %}
                    <div class="form_fields">
                        <div class="ap_question">
                            <p>{{loop.index}}.</p>
                            <p style="display: flex; justify-content: flex-start; align-items: center;  "> {{question.question_text}}</p>
                            <div style=" display:flex; flex-direction:column; justify-content:center; align-items:center">
                                <p style="
                                width: 90px ;margin-left: auto; border: solid 1px black; border-radius:15px;
                                display:flex; justify-content:center; position:sticky;
                                "> 
                                    {{points}} Points
                                </p>
                            </div>
                            
                        </div>
                        <div class="ap_options"></p>
                            {{ form|attr(field_list[loop.index0])(class = 'radio_button') }} 
                        </div>
                        
                    </div> 
                    
                {% endfor %}
                
                {{ form.submit(class = 'ap_submit') }}
                
            </form>
        </div>

   </div>
{% endblock %}